import { FaNodeJs, FaJava, FaChartLine, FaDatabase, FaLink, FaRobot } from "react-icons/fa";
import { TbBrandNextjs, TbSql } from "react-icons/tb";
import {
    SiPython,
    SiPandas,
    SiNumpy,
    SiScikitlearn,
    SiMicrosoftexcel,
    SiLooker,
    SiPowerbi,
    SiTableau,
    SiAnthropic,
    SiOpenai,
    SiGooglegemini,
    SiPowerautomate,
    SiDbt,
    SiMicrosoftazure,
    SiApachespark,
    SiMicrosoftsqlserver,
    SiPostgresql,
    SiGoogleanalytics,
    SiGoogleads,
    SiGoogletagmanager,
    SiMeta,
    SiHubspot,
    SiSalesforce,
    SiSap,
    SiJavascript,
    SiReact,
    SiFastapi,
    SiSelenium,
    SiRobotframework,
    SiDocker,
    SiAmazonaws,
    SiGithub,
    SiJira,
} from "react-icons/si";

// Grouped to match the skills section of the resume
export const TechstackList = [
    {
        category: "Analytics",
        items: [
            { name: "SQL", icon: TbSql },
            { name: "Python", icon: SiPython },
            { name: "pandas", icon: SiPandas },
            { name: "NumPy", icon: SiNumpy },
            { name: "scikit-learn", icon: SiScikitlearn },
            { name: "SAS", icon: FaChartLine },
            { name: "Excel", icon: SiMicrosoftexcel },
        ],
    },
    {
        category: "Dashboards & Self-Serve Reporting",
        items: [
            { name: "Looker", icon: SiLooker },
            { name: "Looker Studio", icon: SiLooker },
            { name: "Power BI", icon: SiPowerbi },
            { name: "Tableau", icon: SiTableau },
        ],
    },
    {
        category: "AI & Automation",
        items: [
            { name: "Claude (Skills, Code, Cowork)", icon: SiAnthropic },
            { name: "OpenAI API", icon: SiOpenai },
            { name: "Gemini API", icon: SiGooglegemini },
            { name: "LangChain", icon: FaLink },
            { name: "n8n", icon: FaRobot },
            { name: "Power Automate", icon: SiPowerautomate },
        ],
    },
    {
        category: "Data Pipelines",
        items: [
            { name: "dbt", icon: SiDbt },
            { name: "Adverity", icon: FaDatabase },
            { name: "Azure Data Factory", icon: SiMicrosoftazure },
            { name: "Apache Spark", icon: SiApachespark },
            { name: "SQL Server", icon: SiMicrosoftsqlserver },
            { name: "PostgreSQL", icon: SiPostgresql },
        ],
    },
    {
        category: "Marketing & Business Data",
        items: [
            { name: "GA4", icon: SiGoogleanalytics },
            { name: "Google Ads", icon: SiGoogleads },
            { name: "Google Tag Manager", icon: SiGoogletagmanager },
            { name: "Meta CAPI", icon: SiMeta },
            { name: "HubSpot", icon: SiHubspot },
            { name: "Salesforce", icon: SiSalesforce },
            { name: "SAP", icon: SiSap },
        ],
    },
    {
        category: "Development & Testing",
        items: [
            { name: "JavaScript", icon: SiJavascript },
            { name: "React", icon: SiReact },
            { name: "Node.js", icon: FaNodeJs },
            { name: "Next.js", icon: TbBrandNextjs },
            { name: "FastAPI", icon: SiFastapi },
            { name: "Java", icon: FaJava },
            { name: "Selenium", icon: SiSelenium },
            { name: "Robot Framework", icon: SiRobotframework },
            { name: "Docker", icon: SiDocker },
            { name: "AWS", icon: SiAmazonaws },
            { name: "Git / GitHub", icon: SiGithub },
            { name: "Jira", icon: SiJira },
        ],
    },
];
